const K='litehub_os_v0';let state=(()=>{try{return JSON.parse(localStorage.getItem(K))||{clients:[],docs:{}}}catch(e){return{clients:[],docs:{}}}})();
const templates={
prospeccao:{title:'Prospecção',intro:'Objetivo: conseguir uma conversa qualificada, não diagnosticar por mensagem.',fields:[['Canal','select',['WhatsApp','Instagram','E-mail','LinkedIn','Indicação','Outro']],['Hipótese de problema','textarea'],['Mensagem inicial','textarea'],['Próximo passo','textarea']]},
analise:{title:'Análise Interna',intro:'Use após o diagnóstico e antes de precificar.',fields:[['Índice SALTO / estágio','input'],['Complexidade','select',['C1 — Simples','C2 — Moderada','C3 — Alta']],['Modo','select',['Exploração','Otimização']],['Maior gargalo','textarea'],['Ponto A','textarea'],['Primeira vitória','textarea'],['Ponto B proposto','textarea'],['Módulos e níveis','textarea'],['UE-I previstas','input'],['UE-R / mês','input'],['Mídia necessária','input'],['Capacidade interna do cliente','select',['Alta','Média','Baixa']],['Red flags','textarea'],['Decisão','select',['Prosseguir para proposta','Solicitar mais informações','Não recomendar contratação']]]},
proposta:{title:'Proposta LiteHub',intro:'A proposta deve parecer uma prescrição baseada no diagnóstico.',fields:[['Ponto A','textarea'],['O que identificamos','textarea'],['Ponto B','textarea'],['Módulos priorizados','textarea'],['Incluído','textarea'],['Não incluído','textarea'],['Duração','input'],['Investimento LiteHub','input'],['Mídia / investimento externo','input'],['Responsabilidades LiteHub','textarea'],['Responsabilidades cliente','textarea'],['Próximo passo','textarea']]},
onboarding:{title:'Onboarding',intro:'Transforma o diagnóstico comercial em fotografia operacional confiável.',checklist:['Contrato/aceite concluído','Pagamento inicial concluído','Responsáveis definidos','Acessos de mídia recebidos','Acesso a site/analytics recebido','CRM/WhatsApp acessado quando aplicável','Histórico de campanhas recebido','Histórico de vendas/atendimento recebido','Materiais de marca recebidos','Orçamento de mídia aprovado','Responsabilidades confirmadas','Ponto A oficial registrado'],fields:[['Pendências / observações','textarea']]},
ciclo:{title:'Ficha do Ciclo SALTO',intro:'Documento central do ciclo.',fields:[['Ponto A oficial','textarea'],['Ponto B esperado','textarea'],['Gargalo prioritário','textarea'],['Primeira vitória','textarea'],['Indicadores','textarea'],['Módulos ativos e níveis','textarea'],['UE planejadas','textarea'],['Responsabilidades LiteHub','textarea'],['Responsabilidades cliente','textarea'],['Orçamento de mídia','input'],['Modo','select',['Exploração','Otimização']],['Data inicial','input'],['Data de revisão','input'],['Hipóteses principais','textarea']]},
update:{title:'Atualização Semanal',intro:'Curta, objetiva e orientada a decisão.',fields:[['Período','input'],['O que aconteceu','textarea'],['Principais números','textarea'],['O que estamos observando','textarea'],['Próximas ações/testes','textarea'],['Dependências do cliente','textarea']]},
pulse:{title:'Pulse de Satisfação',intro:'Embrião do futuro Health Score.',fields:[['Confiança na direção (0–10)','input'],['O que faria subir um ponto?','textarea'],['Saúde','select',['🟢 Saudável','🟡 Atenção','🔴 SOS']],['Risco percebido','textarea'],['Ação de recuperação','textarea']]},
checkpoint:{title:'Checkpoint SALTO',intro:'Decide se a hipótese continua, ajusta ou rotaciona.',fields:[['Avançando para o Ponto B?','select',['Sim','Parcialmente','Não','Sem evidência suficiente']],['Evidências','textarea'],['Manter','textarea'],['Ajustar','textarea'],['Pausar','textarea'],['Nova prioridade','textarea']]},
relatorio:{title:'Relatório Ponto A × Ponto B',intro:'Mostra evolução e aprendizado.',fields:[['Ponto A','textarea'],['O que fizemos','textarea'],['Resultados','textarea'],['O que não funcionou / limitações','textarea'],['Aprendizados','textarea'],['Ponto B','textarea'],['SALTO inicial','input'],['SALTO atual','input'],['Próximo gargalo','textarea'],['Próximo SALTO','textarea']]},
offboarding:{title:'Offboarding',intro:'Encerrar bem também faz parte da experiência LiteHub.',checklist:['Relatório final entregue','Acessos devolvidos/revisados','Ativos confirmados em nome do cliente','Automações documentadas','Pendências financeiras resolvidas','Documentação final entregue','Feedback solicitado','Depoimento/case solicitado quando apropriado','Indicação solicitada quando apropriado'],fields:[['Motivo','select',['Objetivo concluído','Seguirá internamente','Mudança de prioridade','Orçamento','Insatisfação','Outro']],['Orientações finais','textarea'],['Possibilidade de retorno','textarea']]}
};
function save(){localStorage.setItem(K,JSON.stringify(state));refresh()}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function showPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===id));if(id==='templates')renderTemplate()}
document.querySelectorAll('.nav button[data-page]').forEach(b=>b.onclick=()=>showPage(b.dataset.page));
function openClientForm(c=null){clientForm.style.display='block';clientFormTitle.textContent=c?'Editar cliente':'Novo cliente';['clientId','cName','cContact','cScore','cCycle','cPointA','cPointB','cModules','cLinks'].forEach(i=>document.getElementById(i).value='');cStatus.value='Prospect';cStage.value='Eclosão';cComplex.value='C1 — Simples';cHealth.value='⚪ Não avaliado';cProduct.value='Sprint Eclosão';if(c){clientId.value=c.id;cName.value=c.name;cContact.value=c.contact||'';cStatus.value=c.status||'Prospect';cScore.value=c.score||'';cStage.value=c.stage||'Eclosão';cComplex.value=c.complex||'C1 — Simples';cHealth.value=c.health||'⚪ Não avaliado';cCycle.value=c.cycle||'';cProduct.value=c.product||'Sprint Eclosão';cPointA.value=c.pointA||'';cPointB.value=c.pointB||'';cModules.value=c.modules||'';cLinks.value=c.links||''}window.scrollTo({top:0,behavior:'smooth'})}
function closeClientForm(){clientForm.style.display='none'}
cScore.addEventListener('input',e=>{let s=parseFloat(e.target.value);if(!isNaN(s))cStage.value=s>=12?'Escala':s>=9?'Evolução':s>=5?'Tração':'Eclosão'});
function saveClient(){if(!cName.value.trim())return alert('Informe o nome da empresa.');let id=clientId.value||'c_'+Date.now(),o={id,name:cName.value.trim(),contact:cContact.value,status:cStatus.value,score:cScore.value,stage:cStage.value,complex:cComplex.value,health:cHealth.value,cycle:cCycle.value,product:cProduct.value,pointA:cPointA.value,pointB:cPointB.value,modules:cModules.value,links:cLinks.value,updatedAt:new Date().toISOString()},i=state.clients.findIndex(x=>x.id===id);i>=0?state.clients[i]=o:state.clients.push(o);save();closeClientForm()}
function editClient(id){openClientForm(state.clients.find(x=>x.id===id))}function deleteClient(id){if(!confirm('Excluir cliente e documentos salvos?'))return;state.clients=state.clients.filter(x=>x.id!==id);delete state.docs[id];save()}
function renderClients(){clientList.innerHTML=state.clients.length?state.clients.map(c=>`<div class="card client-card"><div><h4>${esc(c.name)}</h4><div class="muted small">${esc(c.contact||'Sem contato')}</div><div class="client-meta"><span class="pill">${esc(c.status)}</span><span class="pill">${esc(c.stage)}</span><span class="pill">${esc(c.complex)}</span><span class="pill">${esc(c.health)}</span></div><p class="small"><b>Ponto B:</b> ${esc(c.pointB||'Não definido')}</p></div><div class="actions"><button class="btn secondary" onclick="editClient('${c.id}')">Editar</button><button class="btn danger" onclick="deleteClient('${c.id}')">Excluir</button></div></div>`).join(''):'<div class="card muted">Nenhum cliente cadastrado.</div>'}
function renderDash(){mTotal.textContent=state.clients.length;mAtivos.textContent=state.clients.filter(c=>['Onboarding','Ciclo ativo','Checkpoint','Revisão','Novo SALTO'].includes(c.status)).length;mComercial.textContent=state.clients.filter(c=>['Reunião agendada','Diagnóstico','Em análise','Proposta','Negociação'].includes(c.status)).length;mRisco.textContent=state.clients.filter(c=>c.health?.includes('🟡')||c.health?.includes('🔴')).length;stageSummary.innerHTML=['Eclosão','Tração','Evolução','Escala'].map(s=>`<div><div class="muted small">${s}</div><div class="metric">${state.clients.filter(c=>c.stage===s).length}</div></div>`).join('');let recent=[...state.clients].sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||'')).slice(0,6);dashboardClients.innerHTML=recent.length?`<table><thead><tr><th>Empresa</th><th>Status</th><th>Estágio</th><th>Saúde</th><th>Ponto B</th></tr></thead><tbody>${recent.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.status)}</td><td>${esc(c.stage)}</td><td>${esc(c.health)}</td><td>${esc(c.pointB||'—')}</td></tr>`).join('')}</tbody></table>`:'<span class="muted">Nenhum registro ainda.</span>'}
function refreshSelect(){let cur=templateClient.value;templateClient.innerHTML='<option value="">Sem cliente selecionado</option>'+state.clients.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');if(state.clients.some(c=>c.id===cur))templateClient.value=cur}
let activeTemplate='prospeccao';function buildTabs(){templateTabs.innerHTML=Object.entries(templates).map(([k,t])=>`<button class="${k===activeTemplate?'active':''}" onclick="activeTemplate='${k}';buildTabs();renderTemplate()">${t.title}</button>`).join('')}
function docStore(cid){state.docs[cid]??={};state.docs[cid][activeTemplate]??={fields:{},checks:{}};return state.docs[cid][activeTemplate]}
function renderTemplate(){let t=templates[activeTemplate],cid=templateClient.value,d=cid?docStore(cid):{fields:{},checks:{}};let h=`<div class="card"><h3>${t.title}</h3><div class="note">${t.intro}</div><hr>`;if(t.checklist)h+=`<div class="checklist">${t.checklist.map((x,i)=>`<label class="check"><input type="checkbox" data-check="${i}" ${d.checks?.[i]?'checked':''} onchange="saveTpl()"><span>${x}</span></label>`).join('')}</div><hr>`;if(t.fields)h+=`<div class="grid cols-2">${t.fields.map((f,i)=>{let v=d.fields?.[i]||'';if(f[1]==='select')return `<div class="field"><label>${f[0]}</label><select data-field="${i}" onchange="saveTpl()">${f[2].map(o=>`<option ${o===v?'selected':''}>${o}</option>`).join('')}</select></div>`;if(f[1]==='textarea')return `<div class="field"><label>${f[0]}</label><textarea data-field="${i}" oninput="saveTpl()">${esc(v)}</textarea></div>`;return `<div class="field"><label>${f[0]}</label><input data-field="${i}" value="${esc(v)}" oninput="saveTpl()"></div>`}).join('')}</div>`;if(!cid)h+='<div class="note warn">Selecione um cliente para salvar este documento.</div>';h+='</div>';templateArea.innerHTML=h}
function saveTpl(){let cid=templateClient.value;if(!cid)return;let d=docStore(cid);document.querySelectorAll('#templateArea [data-field]').forEach(el=>d.fields[el.dataset.field]=el.value);document.querySelectorAll('#templateArea [data-check]').forEach(el=>d.checks[el.dataset.check]=el.checked);localStorage.setItem(K,JSON.stringify(state))}
function exportData(){let b=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='litehub-os-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(a.href)}
function importData(){let f=importFile.files[0];if(!f)return alert('Selecione um JSON.');let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);if(!d.clients||!d.docs)throw 0;state=d;save();alert('Backup importado.')}catch(e){alert('Backup inválido.')}};r.readAsText(f)}function resetAll(){if(confirm('Apagar todos os dados locais?')){state={clients:[],docs:{}};save()}}
function refresh(){renderClients();renderDash();refreshSelect()}buildTabs();refresh();renderTemplate();
